### ISSUE TITLE
NoSuchMethodError: The getter 'coin' was called on null.

### ISSUE THREAD

**Issue by himu007** [KomodoPlatform/atomicDEX#20]
I kept trying to put my full amount of Rick up for swap
Enter details for initial swap amounts
Proceed to next screen
Go back
This allows you to enter a coin amount on the first line without selecting a coin
You can’t do this the first go around
You must first select a coin
But after you back up from the next step you can
Amount on first line with no coin selected
Hit the select coin on second line
Red screen
Back out of app and go back in and it reloads fine though
![image0](https://user-images.githubusercontent.com/8881040/61410631-850cf080-a8dc-11e9-8818-c0dc474c7e4c.png)
**Logs:**
[log (1).txt](https://github.com/KomodoPlatform/atomicDEX/files/3403809/log.1.txt)

**Comment by tonymorony** [comment]
needs to be tested in next release

**Comment by tonymorony** [comment]
Can't reproduce on 0.1.4 so should be fixed

**Comment by lilszi** [comment]
CrisF#3405 reported it is still happening in 0.1.5 he tried a BCH / ETH swap.
![Screenshot_20190809-170120](https://user-images.githubusercontent.com/35148176/62764566-1c053c80-ba86-11e9-922a-b6fe0ccdc2d8.png)

**Comment by Cris-F** [comment]
I upgraded from 0.1.5 - 15dcab0ee to 0.153.  Had 2 failed swaps on that too.
A few hour later I had a BCH ETH swap go through.

**Comment by tonymorony** [comment]
@Cris-F do you have failed swap or exception like above on 0.1.53?
If exception: what are the steps to reproduce?

If you have failed/stuck swaps please use this form: https://forms.gle/e18deJDGYB7M5Ek99

**Comment by Cris-F** [comment]
Hi Tony, 
Yes, I had a failed swap on 0.1.53.  I didn't get the red screen on it though.
I just tried a to buy ETH with BCH.  Failed on step 2/3.  
I'll fill out the form.

**Comment by Cris-F** [comment]
Hi Tony, 
Yes, I had a failed swap on 0.1.53.  I didn't get the red screen on it though.
I just tried a to buy ETH with BCH.  Failed on step 2/3.  
I'll fill out the form.
